//! Hearing an effect without ears.
//!
//! # The one surface a capture cannot photograph
//!
//! Every other check in this toolkit ends with someone looking at a picture.
//! Sound has no picture. A waveform plot shows amplitude over time, which
//! catches an effect that is too quiet or too long and catches nothing else —
//! two sounds with identical envelopes can be a chime and a buzz.
//!
//! So the interesting question is not "how loud" but "what is in it", and that
//! is a spectrum rather than an envelope.
//!
//! # What a naive oscillator does wrong
//!
//! [`Wave::Square`] and [`Wave::Triangle`] are generated by comparing a phase
//! against a threshold. That is the honest shape and it has infinite harmonics:
//! a square at `f` carries partials at `3f, 5f, 7f…` falling off as `1/n`, a
//! triangle the same odd series falling off as `1/n²`.
//!
//! Sampling cannot represent a partial above half the sample rate. It does not
//! drop it — it **reflects** it. A partial at `p` above Nyquist comes back at
//! `sample_rate - p`, and that reflection is not a harmonic of the fundamental
//! or of anything else. A chime with an inharmonic partial sitting under it is
//! precisely what "it sounds nasty" means, and it gets worse as the note gets
//! higher, which is why a bright effect is the one that suffers.
//!
//! At the default 22,050Hz a square at 1200Hz reflects its 19th partial to
//! 199Hz — nearly three octaves *below* the note it belongs to.
//!
//! # Predicted, then measured
//!
//! [`folded_partials`] works out where the reflections land from the wave shape
//! and the sample rate alone. That is arithmetic and could be describing an
//! oscillator this toolkit does not have, so [`aliasing`] renders the voice and
//! measures what is *actually* at those frequencies with an FFT, relative to the
//! fundamental. The prediction says where to look; the spectrum says whether
//! anything is there.

use super::{render_unclamped, SynthConfig, Voice, Wave};

/// Something a listener would notice.
#[derive(Debug, Clone, PartialEq)]
pub enum Fault {
    /// It renders, and there is nothing in it.
    Silent,
    /// Mixed past the limiter, so the peaks are flattened into a crackle.
    Clipped { peak: f32, samples: usize },
    /// The waveform does not sit around zero, which wastes headroom and thumps
    /// when the effect starts and stops.
    OffCentre { offset: f32 },
    /// A step between neighbouring samples big enough to hear as a click,
    /// usually an envelope that did not reach zero before the voice ended.
    Click { step: f32, at_seconds: f32 },
    /// A partial reflected below Nyquist, loud enough to hear under the note.
    Aliased {
        partial_hz: f32,
        folded_to_hz: f32,
        below_fundamental_db: f32,
    },
}

impl Fault {
    pub fn describe(&self) -> String {
        match self {
            Fault::Silent => "renders silence".to_owned(),
            Fault::Clipped { peak, samples } => {
                format!("clips: {} samples, peak {:.2}", samples, peak)
            }
            Fault::OffCentre { offset } => format!("sits {:.3} off zero", offset),
            Fault::Click { step, at_seconds } => {
                format!("jumps {:.2} between samples at {:.3}s", step, at_seconds)
            }
            Fault::Aliased {
                partial_hz,
                folded_to_hz,
                below_fundamental_db,
            } => format!(
                "partial at {:.0}Hz folds back to {:.0}Hz, {:.0}dB under the note",
                partial_hz, folded_to_hz, below_fundamental_db
            ),
        }
    }
}

/// Peak, loudness and shape of a rendered effect.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Measured {
    /// Largest absolute sample *before* the limiter, so an effect mixed too hot
    /// reads above 1.0 rather than being flattened to exactly 1.0.
    pub peak: f32,
    /// Root-mean-square level: how loud it seems, as opposed to how loud its
    /// loudest instant is. A click and a held chord can share a peak.
    pub rms: f32,
    pub dc_offset: f32,
    pub clipped: usize,
    pub worst_step: f32,
    pub worst_step_at: f32,
    pub seconds: f32,
}

/// Measure a rendered buffer. Pass the *unclamped* one — see [`Measured::peak`].
pub fn measure(samples: &[f32], sample_rate: u32) -> Measured {
    let mut peak = 0.0f32;
    let mut sum = 0.0f64;
    let mut square_sum = 0.0f64;
    let mut clipped = 0usize;
    let mut worst_step = 0.0f32;
    let mut worst_index = 0usize;

    for (index, &sample) in samples.iter().enumerate() {
        peak = peak.max(sample.abs());
        sum += sample as f64;
        square_sum += (sample as f64) * (sample as f64);
        if sample.abs() > 1.0 {
            clipped += 1;
        }
        if index > 0 {
            let step = (sample - samples[index - 1]).abs();
            if step > worst_step {
                worst_step = step;
                worst_index = index;
            }
        }
    }

    let count = samples.len().max(1) as f64;
    Measured {
        peak,
        rms: (square_sum / count).sqrt() as f32,
        dc_offset: (sum / count) as f32,
        clipped,
        worst_step,
        worst_step_at: worst_index as f32 / sample_rate as f32,
        seconds: samples.len() as f32 / sample_rate as f32,
    }
}

/// In-place iterative radix-2 FFT. Both halves must be the same power-of-two
/// length; anything else is a caller bug and panics rather than returning noise.
pub fn fft(re: &mut [f32], im: &mut [f32]) {
    let n = re.len();
    assert_eq!(n, im.len(), "the real and imaginary halves must match");
    assert!(n.is_power_of_two(), "radix-2 needs a power-of-two length");
    if n < 2 {
        return;
    }

    // Bit-reversal permutation.
    let mut target = 0usize;
    for source in 1..n {
        let mut bit = n >> 1;
        while target & bit != 0 {
            target ^= bit;
            bit >>= 1;
        }
        target |= bit;
        if source < target {
            re.swap(source, target);
            im.swap(source, target);
        }
    }

    let mut span = 2;
    while span <= n {
        let angle = -std::f32::consts::TAU / span as f32;
        let (step_sin, step_cos) = angle.sin_cos();
        for block in (0..n).step_by(span) {
            let (mut wr, mut wi) = (1.0f32, 0.0f32);
            for offset in 0..span / 2 {
                let a = block + offset;
                let b = a + span / 2;
                let tr = wr * re[b] - wi * im[b];
                let ti = wr * im[b] + wi * re[b];
                re[b] = re[a] - tr;
                im[b] = im[a] - ti;
                re[a] += tr;
                im[a] += ti;
                let next_wr = wr * step_cos - wi * step_sin;
                wi = wr * step_sin + wi * step_cos;
                wr = next_wr;
            }
        }
        span <<= 1;
    }
}

/// Magnitude spectrum of one Hann-windowed frame.
///
/// Bin `k` is `k * sample_rate / frame` Hz. Returns half the frame, since the
/// upper half of a real signal's spectrum is a mirror of the lower.
///
/// The window matters: a rectangular frame of a tone that does not fit a whole
/// number of cycles smears energy across every bin, which would look exactly
/// like the broadband hash this is meant to detect.
pub fn spectrum(samples: &[f32], offset: usize, frame: usize) -> Vec<f32> {
    let mut re = vec![0.0f32; frame];
    let mut im = vec![0.0f32; frame];
    for (index, slot) in re.iter_mut().enumerate().take(frame) {
        let sample = samples.get(offset + index).copied().unwrap_or(0.0);
        let hann = 0.5 - 0.5 * (std::f32::consts::TAU * index as f32 / frame as f32).cos();
        *slot = sample * hann;
    }
    fft(&mut re, &mut im);
    (0..frame / 2)
        .map(|k| (re[k] * re[k] + im[k] * im[k]).sqrt())
        .collect()
}

/// The relative amplitude of each partial a shape generates, `(n, amplitude)`.
///
/// Sine has none. Square and triangle carry the odd series, falling off as
/// `1/n` and `1/n²`. Noise is broadband by definition, so asking where its
/// partials fold is meaningless and the list is empty.
fn partials(wave: Wave) -> Vec<(u32, f32)> {
    let harmonics: Box<dyn Iterator<Item = u32>> = match wave {
        Wave::Sine | Wave::Noise => return Vec::new(),
        Wave::Square | Wave::Triangle => Box::new((3..64).step_by(2)),
    };
    harmonics
        .map(|n| {
            let amplitude = match wave {
                Wave::Square => 1.0 / n as f32,
                _ => 1.0 / (n * n) as f32,
            };
            (n, amplitude)
        })
        .collect()
}

/// Where a note's partials come back, given a sample rate that cannot hold them.
///
/// Returns `(partial_hz, folded_hz, relative_amplitude)` for every partial above
/// Nyquist that reflects to an audible frequency. Pure arithmetic — see
/// [`aliasing`] for the version that checks the rendered signal agrees.
pub fn folded_partials(freq: f32, wave: Wave, sample_rate: u32) -> Vec<(f32, f32, f32)> {
    let nyquist = sample_rate as f32 * 0.5;
    partials(wave)
        .into_iter()
        .filter_map(|(n, amplitude)| {
            let partial = freq * n as f32;
            if partial <= nyquist {
                return None;
            }
            // Reflect repeatedly: a partial above the sample rate itself wraps
            // more than once before it lands.
            let wrapped = partial % sample_rate as f32;
            let folded = if wrapped > nyquist {
                sample_rate as f32 - wrapped
            } else {
                wrapped
            };
            // A reflection that lands on the fundamental or on a real harmonic
            // is inaudible as a separate thing — it reinforces a note already
            // there rather than adding a new one.
            let on_a_harmonic = (folded / freq - (folded / freq).round()).abs() < 0.02;
            if folded < 20.0 || on_a_harmonic {
                return None;
            }
            Some((partial, folded, amplitude))
        })
        .collect()
}

/// Every reflection in a voice loud enough to hear under its own note.
///
/// `floor_db` is how far under the fundamental a reflection may sit before it
/// stops mattering. -32dB is about 2.5% of the note and roughly where a partial
/// stops being masked by it.
///
/// # Predicted, then measured on a signal that can be measured
///
/// [`folded_partials`] says where a *naive* oscillator's partials would land.
/// That is arithmetic about an ideal shape and cannot know what this toolkit
/// actually generates, so it is used only to decide where to look.
///
/// The looking is done on a **steady probe** — a long tone at the voice's
/// highest pitch, with an attack long enough that the analysed frame sits in a
/// flat part of the envelope. That matters more than it sounds. The first
/// version of this measured the effect itself, and game effects are 50–600ms
/// transients: an envelope decaying over a tenth of a second smears every bin
/// far wider than the partials being looked for, and it reported reflections at
/// the level of the note itself for partials whose true amplitude is `1/49²`.
/// The long list was the window describing itself.
///
/// A probe is steady, so the spectrum means what it says, and it exercises the
/// real oscillator rather than an assumption about it.
pub fn aliasing(voice: &Voice, config: &SynthConfig, floor_db: f32) -> Vec<Fault> {
    // A glide aliases worst at the top of its sweep; the average would miss a
    // rise that only turns nasty at the end.
    let (top, _) = voice.highest_audible();
    let predicted = folded_partials(top, voice.shape(), config.sample_rate);
    if predicted.is_empty() {
        return Vec::new();
    }

    let probe = Voice::tone(0.0, 0.5, top, 1.0)
        .wave(voice.shape())
        .attack(0.5);
    let rendered = render_unclamped(&[probe], config, 0x5EED);
    let frame = usable_frame(rendered.len());
    if frame < 64 || rendered.len() < frame {
        return Vec::new();
    }
    // The flattest part of the envelope: the peak, halfway through.
    let offset = (rendered.len() / 2).saturating_sub(frame / 2);
    let bins = spectrum(&rendered, offset, frame);
    let hz_per_bin = config.sample_rate as f32 / frame as f32;

    let fundamental = magnitude_near(&bins, top, hz_per_bin);
    if fundamental <= f32::EPSILON {
        return Vec::new();
    }

    predicted
        .into_iter()
        .filter_map(|(partial, folded, _)| {
            let level = 20.0
                * (magnitude_near(&bins, folded, hz_per_bin) / fundamental)
                    .max(1e-9)
                    .log10();
            (level > floor_db).then_some(Fault::Aliased {
                partial_hz: partial,
                folded_to_hz: folded,
                below_fundamental_db: level,
            })
        })
        .collect()
}

/// What an FFT of the rendered voice finds at each predicted fold, in dB under
/// the fundamental.
///
/// Only trustworthy for a steady tone — see [`aliasing`] for why. Its purpose is
/// to check that the closed form above matches the oscillator this toolkit
/// actually has, which is a thing a test can arrange and a game effect cannot.
pub fn measured_aliasing(voice: &Voice, config: &SynthConfig) -> Vec<(f32, f32)> {
    let (top, at) = voice.highest_audible();
    let predicted = folded_partials(top, voice.shape(), config.sample_rate);
    if predicted.is_empty() {
        return Vec::new();
    }

    let rendered = render_unclamped(&[*voice], config, 0x5EED);
    let frame = usable_frame(rendered.len());
    if frame < 64 || rendered.len() < frame {
        return Vec::new();
    }
    let centre = (at * config.sample_rate as f32) as usize;
    let offset = centre.saturating_sub(frame / 2).min(rendered.len() - frame);
    let bins = spectrum(&rendered, offset, frame);
    let hz_per_bin = config.sample_rate as f32 / frame as f32;

    let fundamental = magnitude_near(&bins, top, hz_per_bin);
    if fundamental <= f32::EPSILON {
        return Vec::new();
    }
    predicted
        .into_iter()
        .map(|(_, folded, _)| {
            let measured = magnitude_near(&bins, folded, hz_per_bin);
            (folded, 20.0 * (measured / fundamental).max(1e-9).log10())
        })
        .collect()
}

/// The largest power-of-two frame the buffer can fill, capped so a long effect
/// is still analysed over a slice short enough that its pitch has not moved.
fn usable_frame(samples: usize) -> usize {
    let mut frame = 2048;
    while frame > samples && frame > 32 {
        frame >>= 1;
    }
    frame.min(2048)
}

/// Peak magnitude within a bin either side, so a note that falls between bins is
/// not read as absent.
fn magnitude_near(bins: &[f32], hz: f32, hz_per_bin: f32) -> f32 {
    let centre = (hz / hz_per_bin).round() as isize;
    (-1..=1)
        .filter_map(|d| usize::try_from(centre + d).ok())
        .filter_map(|k| bins.get(k))
        .fold(0.0f32, |worst, &m| worst.max(m))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config() -> SynthConfig {
        SynthConfig::default()
    }

    /// The transform itself, against a signal whose answer is known by hand.
    #[test]
    fn a_pure_tone_lands_in_one_bin() {
        let rate = 22_050u32;
        let frame = 1024;
        // Exactly 64 cycles in the frame, so it sits on bin 64 with no leakage.
        let hz = 64.0 * rate as f32 / frame as f32;
        let samples: Vec<f32> = (0..frame)
            .map(|i| (std::f32::consts::TAU * hz * i as f32 / rate as f32).sin())
            .collect();
        let bins = spectrum(&samples, 0, frame);

        let loudest = bins
            .iter()
            .enumerate()
            .max_by(|a, b| a.1.partial_cmp(b.1).unwrap())
            .map(|(k, _)| k)
            .unwrap();
        assert_eq!(loudest, 64, "a tone at bin 64 was found at {}", loudest);
        // And nothing anywhere else: a bin two away should be far down.
        assert!(bins[70] < bins[64] * 0.01);
    }

    #[test]
    fn the_transform_is_reversible_enough_to_trust() {
        // Parseval: the energy in the bins matches the energy in the samples.
        let frame = 256;
        let samples: Vec<f32> = (0..frame)
            .map(|i| ((i * 7) % 13) as f32 / 13.0 - 0.5)
            .collect();
        let mut re = samples.clone();
        let mut im = vec![0.0; frame];
        fft(&mut re, &mut im);
        let time: f32 = samples.iter().map(|s| s * s).sum();
        let freq: f32 = re
            .iter()
            .zip(&im)
            .map(|(r, i)| (r * r + i * i) / frame as f32)
            .sum();
        assert!((time - freq).abs() / time < 0.001, "{} vs {}", time, freq);
    }

    /// A sine has no partials to fold, at any pitch.
    #[test]
    fn a_sine_never_aliases() {
        for hz in [200.0, 1200.0, 4000.0, 9000.0] {
            assert!(folded_partials(hz, Wave::Sine, 22_050).is_empty(), "{}", hz);
            let voice = Voice::tone(0.0, 0.3, hz, 0.5);
            assert!(aliasing(&voice, &config(), -60.0).is_empty(), "{}", hz);
        }
    }

    /// The disproof: hand-build the naive oscillator this toolkit used to have
    /// and check the measurement finds its reflections.
    ///
    /// Without this the audit could be broken rather than the sound clean, and
    /// the two look identical from the outside. A phase-threshold square at
    /// 1200Hz in a 22kHz stream must show energy where `folded_partials` says.
    #[test]
    fn the_measurement_finds_a_naive_oscillator_folding() {
        let rate = 22_050u32;
        let hz = 1200.0f32;
        let naive: Vec<f32> = (0..4096)
            .map(|i| {
                let phase = (hz * i as f32 / rate as f32).fract();
                if phase < 0.5 {
                    1.0
                } else {
                    -1.0
                }
            })
            .collect();
        let bins = spectrum(&naive, 0, 2048);
        let hz_per_bin = rate as f32 / 2048.0;
        let fundamental = magnitude_near(&bins, hz, hz_per_bin);

        let folds = folded_partials(hz, Wave::Square, rate);
        assert!(!folds.is_empty(), "1200Hz must fold in a 22kHz stream");
        let loudest = folds
            .iter()
            .map(|&(_, folded, _)| {
                20.0 * (magnitude_near(&bins, folded, hz_per_bin) / fundamental)
                    .max(1e-9)
                    .log10()
            })
            .fold(f32::MIN, f32::max);
        assert!(
            loudest > -32.0,
            "a naive square's loudest reflection measured {:.0}dB under the              note — the detector cannot see aliasing that is certainly there",
            loudest
        );
    }

    /// And the oscillator this toolkit actually has does not fold at all.
    ///
    /// Same pitch, same shape, same measurement as the test above. The only
    /// difference is that the partials above Nyquist are never generated.
    #[test]
    fn the_band_limited_oscillator_does_not_fold() {
        let voice = Voice::tone(0.0, 0.5, 1200.0, 0.9)
            .wave(Wave::Square)
            .attack(0.5);
        let measured = measured_aliasing(&voice, &config());
        assert!(!measured.is_empty(), "nothing was predicted to measure");
        let loudest = measured.iter().map(|&(_, db)| db).fold(f32::MIN, f32::max);
        assert!(
            loudest < -60.0,
            "the loudest reflection is {:.0}dB under the note; band-limiting              should leave nothing there at all",
            loudest
        );
        assert!(aliasing(&voice, &config(), -32.0).is_empty());
    }

    /// A low square keeps every partial under Nyquist and is clean.
    #[test]
    fn a_low_square_has_room_for_its_partials() {
        assert!(aliasing(
            &Voice::tone(0.0, 0.3, 90.0, 0.5).wave(Wave::Square),
            &config(),
            -40.0
        )
        .is_empty());
    }

    #[test]
    fn measuring_finds_the_shape_of_a_buffer() {
        let flat = vec![0.5f32; 100];
        let m = measure(&flat, 100);
        assert!((m.peak - 0.5).abs() < 1e-6);
        assert!((m.dc_offset - 0.5).abs() < 1e-6, "a constant is all offset");
        assert_eq!(m.clipped, 0);

        let hot = vec![1.4f32; 10];
        assert_eq!(measure(&hot, 100).clipped, 10);

        let mut stepped = vec![0.0f32; 50];
        stepped[25] = 0.9;
        assert!(measure(&stepped, 100).worst_step >= 0.9);
    }
}
